// Restored from the original CONTENT.md, with short teaching steps and new practice.
// Choices contain no correctness flags; the shared primary answer drives scoring.
const skillLabels = {
  'alphabetical-order': 'Alphabetical order', 'guide-words': 'Guide words',
  definition: 'Definitions', context: 'Words in context', 'related-words': 'Related words',
  'entry-layout': 'Inside an entry', spelling: 'Spelling',
  'multiple-meanings': 'Multiple meanings', 'part-of-speech': 'Parts of speech'
};
const lesson = (id, difficulty, category, skill, prompt, question, answer, choices, tip, success, extra = {}) => ({
  id, source: 'lesson', difficulty, category, subcategory: skillLabels[skill],
  type: 'multiple-choice', dictionarySkill: skill, literacyObjective: 'use-dictionary-independently',
  theme: 'literacy', prompt, question, answer, choices, tip, success, ...extra
});

export const lessons = [
  lesson('alphabetical-order', 'Easy', 'Dictionary Skills', 'alphabetical-order',
    'Open your dictionary. Notice how words follow A–Z order.', 'Which word would come first?',
    'read', ['read', 'resource', 'Rotary'],
    'Compare the first letters. If they match, move to the next letter until you find a difference.',
    'Read comes first: after the shared r, e comes before o; then a comes before s.'),
  lesson('community-guide-words', 'Easy', 'Dictionary Skills', 'guide-words',
    'Find the two guide words at the top of a page in your book. Now try this example.',
    'Would COMMUNITY fit between the guide words COMBINE and COMPANY?',
    'Yes', ['Yes', 'No'],
    'Guide words are the first and last words on a page. A word belongs there if it falls between them in alphabetical order.',
    'Community comes after combine and before company. Guide words help you choose the right page.',
    { type: 'yes-no', guideWords: ['combine', 'company'], rotaryContext: 'Rotary Clubs serve the communities where their members live and work.' }),
  lesson('volunteer-definition', 'Easy', 'Word Hunt', 'definition',
    'Find VOLUNTEER in your dictionary. Read what it means.', 'Which description is closest to the meaning?',
    'Someone who freely chooses to help', ['Someone who freely chooses to help', 'Someone who sells an item', 'Someone who wins a prize'],
    'Open near V. Use the guide words to narrow your search, then read the definition beside the word.',
    'Volunteers choose to give their time or effort. Reading the definition helps you understand an unfamiliar word.',
    { rotaryContext: 'Rotary volunteers help with literacy and other projects in their communities.' }),
  lesson('cooperate-context', 'Easy', 'Word Hunt', 'context',
    'Find COOPERATE in your dictionary and read its meaning.', 'Which situation shows people cooperating?',
    'People working together to clean a park', ['People working together to clean a park', 'People refusing to help each other', 'People leaving before a project starts'],
    'Read the definition, then think about what the people in each answer are doing.',
    'Cooperation means working together. You used a dictionary meaning in an everyday situation.',
    { rotaryContext: 'Rotary Clubs cooperate with schools and other clubs on projects nearby and around the world.' }),
  lesson('leader-related-words', 'Easy', 'Word Families', 'related-words',
    'Find LEADER in your dictionary. Look at nearby words, too.', 'Which word belongs to the same word family?',
    'leadership', ['leadership', 'leaf', 'leather'],
    'Related words often share a starting part and a connected meaning. Check both in your book.',
    'Leader and leadership share a word family. Nearby entries can help you grow your vocabulary.'),
  lesson('alphabet-first-letter', 'Easy', 'Dictionary Skills', 'alphabetical-order',
    'Open your dictionary and look at the letter sections.', 'Which word would you look for nearest the beginning of the dictionary?',
    'apple', ['zebra', 'apple', 'moon'],
    'Say the alphabet slowly. Words starting with earlier letters come earlier in the book.',
    'Apple begins with A. Looking at the first letter helps you choose where to open the book.'),
  lesson('guide-word-purpose', 'Easy', 'Dictionary Skills', 'guide-words',
    'Look at the two guide words at the top of a page in your dictionary.', 'What do guide words help you do?',
    'Choose the page where a word belongs', ['Choose the page where a word belongs', 'Count the pictures in the book', 'Find the name of the author'],
    'Compare each guide word with the first and last entries printed on that page.',
    'The guide words mark the first and last entries. Check them before reading every word on a page.'),
  lesson('entry-headword', 'Easy', 'Dictionary Skills', 'entry-layout',
    'Open any page of word entries. Look for the words printed in bold.', 'What does the bold word at the start of an entry tell you?',
    'Which word the entry explains', ['Which word the entry explains', 'How many pages are in the book', 'Who owns the dictionary'],
    'An entry is the small section of information about one word. Notice where it starts.',
    'The headword names the entry. Its spelling, pronunciation, and meaning can help you read and write.'),
  lesson('kind-meaning', 'Easy', 'Word Hunt', 'definition',
    'Find KIND in your dictionary. Read the meaning that describes a person.', 'Which person is being kind?',
    'Someone helping a friend who is hurt', ['Someone helping a friend who is hurt', 'Someone hiding a friend’s book', 'Someone pushing ahead in line'],
    'Some words have more than one meaning. Look for the meaning that describes how a person acts.',
    'Kind can describe someone who cares about others. The situation helps you choose the right meaning.'),
  lesson('help-word-family', 'Easy', 'Word Families', 'related-words',
    'Find HELP in your dictionary. Look for words that start the same way.', 'Which word is in the same family as HELP?',
    'helpful', ['helpful', 'helmet', 'hello'],
    'Look for the whole starting word, then check that the meanings are connected.',
    'Helpful belongs to the help word family. Word parts give you clues about new vocabulary.'),
  lesson('play-word-family', 'Easy', 'Word Families', 'related-words',
    'Find PLAY in your dictionary. Read the nearby entries.', 'Which word is related to PLAY?',
    'playful', ['plate', 'playful', 'place'],
    'Words can start with similar letters without having related meanings. Check the meaning as well.',
    'Play and playful have connected meanings. Checking the definition is better than guessing from a few letters.'),
  lesson('book-spelling', 'Easy', 'Word Hunt', 'spelling',
    'Find the word that sounds like “frend” in your dictionary’s F section. Look carefully at its letters.', 'Which spelling matches the headword in your book?',
    'friend', ['freind', 'friend', 'frend'],
    'Point to each letter in the headword and compare it with each answer. Take your time.',
    'Friend is the spelling in the dictionary. A headword is a useful spelling check when you write.'),
  lesson('service-multiple-meanings', 'Medium', 'Word Hunt', 'multiple-meanings',
    'Find SERVICE in your dictionary. Read its different meanings.',
    'Which meaning fits “The club organized a service project to improve the park”?',
    'Helping or work done for others', ['Helping or work done for others', 'A religious ceremony', 'Maintaining a machine', 'A tennis serve'],
    'Read the whole sentence. Think about what the club is doing for the park before choosing a meaning.',
    'The sentence points to work done for others. Context helps you choose between dictionary meanings.',
    { rotaryContext: 'Rotary Clubs organize service projects based on needs in their communities.' }),
  lesson('generous-part-of-speech', 'Medium', 'Dictionary Skills', 'part-of-speech',
    'Find GENEROUS in your dictionary. Look for a part-of-speech label.', 'What kind of word is GENEROUS?',
    'Adjective', ['Noun', 'Verb', 'Adjective', 'Adverb'],
    'Look beside the headword for a label such as n., v., or adj. The dictionary’s introduction explains these abbreviations.',
    'Generous is an adjective: it describes a person. Entry labels help you see how to use words in a sentence.',
    { rotaryContext: 'Generosity can include giving time, skills, or resources to help others.' }),
  lesson('bank-context', 'Medium', 'Word Hunt', 'multiple-meanings',
    'Find BANK in your dictionary and read its meanings.', 'Which meaning fits “We sat on the bank beside the river”?',
    'The land beside a river', ['The land beside a river', 'A place that keeps money', 'To rely on something'],
    'Look for clues in the sentence, then compare them with the different definitions.',
    'River tells you which meaning of bank fits. Reading beyond the first definition helps you understand a sentence.'),
  lesson('quiet-part-of-speech', 'Medium', 'Dictionary Skills', 'part-of-speech',
    'Find QUIET in your dictionary. Read the entry labels and meanings.', 'In “a quiet room,” what job does QUIET do?',
    'Adjective: it describes the room', ['Adjective: it describes the room', 'Noun: it names a person', 'Verb: it tells an action'],
    'A word may have several jobs. Use the sentence and the entry labels to pick the one that fits.',
    'Quiet describes the room here, so it acts as an adjective. A dictionary can help you use a word accurately.')
];

export const independentDiscovery = {
  title: 'Your own discovery',
  prompt: 'Find a word in your dictionary that you did not know before today. Read its definition.',
  action: 'I found a new word!',
  success: 'That’s what resourceful learners do—they know where to look when they want to learn something new.'
};
