"""Regenerate browser content from the supplied CSV; no third-party packages."""
import csv
import json
from pathlib import Path

root = Path(__file__).resolve().parent.parent
with (root / 'content/dictionary-quiz.csv').open(newline='', encoding='utf-8-sig') as source:
    rows = list(csv.DictReader(source))

assert len(rows) == 99
assert {int(row['#']) for row in rows} == set(range(1, 100))
questions = []
for row in rows:
    assert row['Difficulty'] in ('Easy', 'Medium', 'Hard')
    assert row['Question'].strip() and row['Answer'].strip()
    skill = (row['Subcategory'].lower().replace(' ', '-') if row['Category'] == 'Dictionary Skills'
             else 'definition' if row['Category'] == 'Word Hunt' else 'reference-lookup')
    question = row['Question'].strip()
    if row['#'] == '12':
        question = 'Look up omnivore. How many types of foods are listed in the definition?'
    questions.append({
        'id': int(row['#']),
        'category': row['Category'],
        'subcategory': row['Subcategory'],
        'difficulty': row['Difficulty'],
        'type': 'typed-answer',
        'dictionarySkill': skill,
        'literacyObjective': 'interpret-entry' if skill == 'definition' else 'find-and-read-information',
        'theme': row['Subcategory'],
        'prompt': 'Use your physical dictionary to find the answer.',
        'question': question,
        'answer': row['Answer'].strip(),
        'success': 'Great find! Keep exploring your dictionary.',
    })

output = '// Generated by scripts/import-questions.py from content/dictionary-quiz.csv.\n'
output += 'export const importedQuestions = ' + json.dumps(questions, ensure_ascii=False, indent=2) + ';\n'
(root / 'src/content/imported-questions.js').write_text(output, encoding='utf-8')
